### ISSUE TITLE
Add support for launching Microsoft Edge

### ISSUE THREAD

**Issue by auchenberg** [caspervonb/node-browser_process#34]
In order to launch Microsoft Edge, we are providing https://github.com/MicrosoftEdge/edge-launch, and [edge-diagnostics-launch](https://github.com/Microsoft/edge-diagnostics-launch) when remote debugging is needed to be enabled.

The process for launching Edge is slightly different than other browsers, as our binaries doesn't support flags directly, and remote debugging is happening via a protocol adaptor.

**Comment by caspervonb** [comment]
Check your inbox for a more elaborate response, preliminary implementation of a edge launcher is at [https://github.com/codajs/coda-edge](https://github.com/codajs/coda-edge).

At this point I'm considering this module a failed experiment, normalizing arguments isn't really doable. And it's beyond the scope of this module to bring in protocol adapters.

Amok v2 (Coda) is just going to have specialized launchers as plugins (bundled with the distro by default) which just do _do the right_ thing and let you pass extra arguments as-is.

**Comment by auchenberg** [comment]
Makes sense. I'd like the new modular approach. This one has grown organically.
